# Your telegram bot credential file. Required.
bot_credential_file: bot_credential.yaml

# Set the path to the tarot data file. Required.
tarot_data: tarot_data.json

# Enable or disable debug mode. Optional.
# debug: false

# Set your telegram user id if you want to restrict access to the bot. Optional.
# username_whitelist: []
